package com.mohasihab.todolistcompose.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF005FAF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD4E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C3A)
val md_theme_light_secondary = Color(0xFF545F71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E3F8)
val md_theme_light_onSecondaryContainer = Color(0xFF111C2B)
val md_theme_light_tertiary = Color(0xFF6E5676)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF7D8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF271430)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFFA5C8FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF005FAF)
val md_theme_light_outlineVariant = Color(0xFFC3C6CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA5C8FF)
val md_theme_dark_onPrimary = Color(0xFF00315F)
val md_theme_dark_primaryContainer = Color(0xFF004786)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_secondary = Color(0xFFBCC7DC)
val md_theme_dark_onSecondary = Color(0xFF273141)
val md_theme_dark_secondaryContainer = Color(0xFF3D4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E3F8)
val md_theme_dark_tertiary = Color(0xFFDABDE2)
val md_theme_dark_onTertiary = Color(0xFF3D2946)
val md_theme_dark_tertiaryContainer = Color(0xFF553F5D)
val md_theme_dark_onTertiaryContainer = Color(0xFFF7D8FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inversePrimary = Color(0xFF005FAF)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA5C8FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF005FAF)


val Green = Color(0xFF00C049)
val orange = Color(0xFFFB5600)
val blue = Color(0xFF314561)
val light_Green = Color(0xFF006E26)
val light_onGreen = Color(0xFFFFFFFF)
val light_GreenContainer = Color(0xFF6CFF82)
val light_onGreenContainer = Color(0xFF002106)
val dark_Green = Color(0xFF44E266)
val dark_onGreen = Color(0xFF003910)
val dark_GreenContainer = Color(0xFF00531B)
val dark_onGreenContainer = Color(0xFF6CFF82)
val light_orange = Color(0xFFA93700)
val light_onorange = Color(0xFFFFFFFF)
val light_orangeContainer = Color(0xFFFFDBCF)
val light_onorangeContainer = Color(0xFF380D00)
val dark_orange = Color(0xFFFFB59B)
val dark_onorange = Color(0xFF5B1A00)
val dark_orangeContainer = Color(0xFF812800)
val dark_onorangeContainer = Color(0xFFFFDBCF)
val light_Blue = Color(0xFF1B60A5)
val light_onBlue = Color(0xFFFFFFFF)
val light_BlueContainer = Color(0xFFD4E3FF)
val light_onBlueContainer = Color(0xFF001C39)
val dark_Blue = Color(0xFFA4C9FF)
val dark_onBlue = Color(0xFF00315D)
val dark_BlueContainer = Color(0xFF004884)
val dark_onBlueContainer = Color(0xFFD4E3FF)
